### ISSUE TITLE
Docker client needs to connect InCluster Minio from outside the k8s cluster

### ISSUE THREAD

**Issue by Ghostbaby** [goharbor/harbor-cluster-operator#118]
Use docker push image to harbor registry, docker client needs to connect `minio` API to HEAD object. 
If the S3 connection information we pass to the registry is k8s service name, docker client will use k8s service name to connect minio , and it is clear that the client cannot connect the k8s service name.

![image](https://user-images.githubusercontent.com/3281480/87315779-6a08a700-c557-11ea-96ad-3e7991988197.png)

**Comment by steven-zou** [comment]
As linked issue https://github.com/goharbor/harbor-operator/issues/63 has been closed, this issue can also be closed now.
