### ISSUE TITLE
Provide a interface template for covering the LCM of the relying on CRs

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-cluster-operator#15]
something like:

```go
type CRLCMController interface {
  Provision(cr *CRD) error
  Delete(uid UUID) error
  Get(uid UUID)(*CRD, error)
  Update(oldCR *CRD, newCR *CRD) error // including scale?
}
```

**Comment by Ghostbaby** [comment]
type CRLCMController interface {
	Reconcile() *reconciler.Results
	Deploy() error
	Readiness() error
	DownScale() error
	RollingUpgrades()
}

**Comment by steven-zou** [comment]
```go

type CRStatus struct {
  Phase string
  // ---
}
```

**Comment by Ghostbaby** [comment]
```go
type CRStatus struct {
	Phase           Phase  `json:"phase,omitempty"`
	ExternalService string `json:"service,omitempty"`
	AvailableNodes  int32  `json:"availableNodes,omitempty"`
}

type Phase string

const (
	PendingPhase Phase = "Pending"
	ReadyPhase   Phase = "Ready"
	UpgradePhase Phase = "Upgrade"
	DestroyPhase Phase = "Destroy"
)
```
Phase 
- Pending, The reconcile has created CR , but the CR has not been scheduled yet.
- Ready,The CR has been deployed, the number of nodes is as expected, and the service is available.
- Upgrade, The CR is processing upscale、downscale、rollingupdate.
- Destroy, The CR is destroying.

**Comment by steven-zou** [comment]
@Ghostbaby 

Why do we need `ExternalService` in the status spec?

**Comment by Ghostbaby** [comment]
@steven-zou We need to expose the connection information of each component to HarborCluster Reconcile,  reconcile can tell the harbor operator how to access redis, pg, etc.
